Repository IUT-LYON1-VUEJS-GROUPE4/VUE3-Chat-Client, pull requests merged in 2022-11, with the labels that each got.

#93 Step 6 completed
  src/components/Conversation/Conversation.vue
  src/components/Message/Message.vue
  src/composables/emits.ts
  src/composables/events.ts
Labels: Step completed

#110 Step 7 completed
  src/components/Community/Community.vue
  src/components/Conversation/Conversation.vue
  src/components/Search/Search.css
  src/components/Search/Search.vue
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.vue
  src/composables/events.ts
  src/stores/messenger.ts
Labels: Step completed

#119 Fix new message sidebar
  src/components/Conversation/Conversation.vue
  src/components/Sidebar/Sidebar.vue
Labels: conflit

#116 fix conversation title + green circle in conversation and sidebar
  src/components/Conversation/Conversation.vue
  src/components/Sidebar/Sidebar.vue
  src/stores/messenger.ts
Labels: invalid

#126 Step 8 completed
  .github/workflows/eslint.yml
  src/assets/base.css
  src/client/test.js
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/Message/Message.css
  src/components/Message/Message.vue
  src/components/Search/Search.css
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/stores/messenger.ts
  tsconfig.json
Labels: Step completed

#140 set title conversation
  index.html
  src/components/Conversation/Conversation.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/stores/messenger.ts
Labels: conflit

#145 Step 9 completed
  .github/workflows/eslint.yml
  index.html
  src/client/types/events.ts
  src/components/Community/Community.vue
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/Message/Message.css
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/stores/messenger.ts
Labels: Step completed

#162 Step 10 completed
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/Group/Group.vue
  src/components/Message/Message.vue
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/stores/messenger.ts
Labels: Step completed
