Repository IUT-LYON1-VUEJS-GROUPE4/VUE3-Chat-Client, pull requests merged in 2022-10, with the labels that each got.

#7 Group information page
  src/components/Community/Community.vue
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/GroupInformation/GroupInformation.css
  src/components/GroupInformation/GroupInformation.vue
  src/router/index.ts
  src/stores/messenger.ts
Labels: no-merge

#9 Step 1 completed
  .eslintrc.cjs
  .github/workflows/codeql.yml
  index.html
  src/client/client.ts
  src/client/types/emits.ts
  src/components/Community/Community.vue
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/GroupInformation/GroupInformation.css
  src/components/GroupInformation/GroupInformation.vue
  src/composables/emits.ts
  src/router/index.ts
  src/stores/messenger.ts
  yarn.lock
Labels: Step completed

#14 Step 2 completed
  src/App.vue
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/stores/messenger.ts
Labels: Step completed

#16 display messages
  src/components/Conversation/Conversation.vue
Labels: conflit

#21 Fix send message
  src/components/Conversation/Conversation.vue
  src/composables/emits.ts
Labels: do not merge this

#19 Message Component
  src/assets/reacts.json
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/Message/Message.css
  src/components/Message/Message.vue
  tsconfig.json
Labels: do not merge this

#20 fix group information page + currentConversationId
  src/App.vue
  src/components/Conversation/Conversation.vue
  src/components/GroupInformation/GroupInformation.vue
Labels: do not merge this

#24 Step 3 completed
  .eslintrc.cjs
  .prettierrc.json
  index.html
  src/App.vue
  src/assets/reacts.json
  src/client/client.ts
  src/client/test.js
  src/client/types/business.ts
  src/client/types/emits.ts
  src/client/types/events.ts
  src/client/useLowLevelClient.ts
  src/components/Auth/Auth.css
  src/components/Auth/Auth.vue
  src/components/Community/Community.css
  src/components/Community/Community.vue
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/Group/Group.css
  src/components/Group/Group.vue
  src/components/GroupInformation/GroupInformation.css
  src/components/GroupInformation/GroupInformation.vue
  src/components/Message/Message.css
  src/components/Message/Message.vue
  src/components/Search/Search.css
  src/components/Search/Search.vue
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/router/index.ts
  src/stores/auth.ts
  src/stores/messenger.ts
  tsconfig.config.json
  tsconfig.json
  vite.config.ts
Labels: Step completed

#59 Sort Members and No-Members from Conversation
  src/components/Group/Group.vue
Labels: do not merge this

#65 Step 4 completed
  src/components/Community/Community.vue
  src/components/Group/Group.vue
  src/components/GroupInformation/GroupInformation.vue
  src/components/Message/Message.vue
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/stores/messenger.ts
Labels: Step completed

#76 fix display reply message
  src/components/Message/Message.vue
Labels: conflit

#80 Step 5 completed
  src/client/types/emits.ts
  src/components/Conversation/Conversation.css
  src/components/Conversation/Conversation.vue
  src/components/GroupInformation/GroupInformation.vue
  src/components/Message/Message.css
  src/components/Message/Message.vue
  src/components/Sidebar/Sidebar.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/stores/messenger.ts
Labels: Step completed
